/*! CO2 Application by toppersystem.com | Author: Andrea Bagordo | (c) toppersytem.com | https://www.gnu.org/licenses/gpl-3.0.html */
<!--
function ControllerFunctionTS(){if((document.getElementById('clhts'))&&(document.getElementById('rsdts'))){var result=true;}else{var result=false;}
return result;}
function DecodeHTMLentytiesTS(html){var txt=document.createElement("textarea");txt.innerHTML=html;return txt.value;}
function CloseResultCo2TS(){if(ControllerFunctionTS()==true){if(document.getElementById('co2tsresult')){var p=document.getElementById('co2tsresult');document.body.removeChild(p);setTimeout("startco2ts()",80);}}}
function BodySizeCalculateTS(lang){if(ControllerFunctionTS()==true){if(lang){var txtts1;if(lang=="it"){txtts1="Attendere il completamento del calcolo";}else if(lang=="ar"){txtts1="انتظر حتى يكتمل الحساب";}else if(lang=="de"){txtts1="Warten Sie, bis die Berechnung abgeschlossen ist";}else if(lang=="es"){txtts1="Espere a que se complete el cálculo";}else if(lang=="fr"){txtts1="Attendre la fin du calcul";}else if(lang=="hi"){txtts1="गणना पूर्ण होने की प्रतीक्षा करें ";}else if(lang=="ja"){txtts1="計算が完了するのを待ちます";}else if(lang=="pl"){txtts1="Poczekaj na zakończenie obliczeń";}else if(lang=="pt"){txtts1="Espere que o cálculo termine";}else if(lang=="ru"){txtts1="Дождитесь завершения расчета";}else if(lang=="zh"){txtts1="等待计算完成";}else if(lang=="he"){txtts1="המתן לסיום החישוב";}else if(lang=="la"){txtts1="Calculum expectare perfectum";}else{txtts1="Wait for the calculation to complete";}
var p=document.getElementById('co2ts');document.body.removeChild(p);var add=document.createElement("div");add.setAttribute("id","co2tsresult");add.setAttribute("class","co2tsresult animate_y_bottom_toppersystem");add.innerHTML="<span>&#127811; "+txtts1+"</span>";document.body.appendChild(add);if((parseFloat(document.getElementById('clhts').value.trim())==0)){if(document.getElementById('auurlts')){if(document.getElementById('auurlts').value.trim()!=""){var url=document.getElementById('auurlts').value.trim();var val_header_send_toppersystem="";var randInt=Math.floor(Math.random()*10);if(randInt=="0"){val_header_send_toppersystem="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:72.0; toppersystemnet) Gecko/20100101 Firefox/72.0";}else if(randInt=="1"){val_header_send_toppersystem="Mozilla/5.0 (Windows NT 10.0; Win64; x64; toppersystemnet) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36";}else if(randInt=="2"){val_header_send_toppersystem="Mozilla/5.0 (Windows NT 10.0; WOW64; toppersystemnet) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36";}else if(randInt=="3"){val_header_send_toppersystem="Mozilla/5.0 (Windows NT 10.0; toppersystemnet) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36";}else if(randInt=="4"){val_header_send_toppersystem="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0; toppersystemnet) Gecko/20100101 Firefox/116.0";}else if(randInt=="5"){val_header_send_toppersystem="Mozilla/5.0 (Macintosh; Intel Mac OS X 13.5; rv:109.0; toppersystemnet) Gecko/20100101 Firefox/116.0";}else if(randInt=="6"){val_header_send_toppersystem="Mozilla/5.0 (X11; Linux i686; rv:109.0; toppersystemnet) Gecko/20100101 Firefox/116.0";}else if(randInt=="7"){val_header_send_toppersystem="Mozilla/5.0 (Macintosh; Intel Mac OS X 13_5; toppersystemnet) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Safari/605.1.15";}else if(randInt=="8"){val_header_send_toppersystem="Mozilla/5.0 (Macintosh; Intel Mac OS X 13_5; toppersystemnet) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/115.0.1901.203";}else if(randInt=="9"){val_header_send_toppersystem="Mozilla/5.0 (Windows NT 10.0; Win64; x64; toppersystemnet) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/115.0.1901.203";}else if(randInt=="10"){val_header_send_toppersystem="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:72.0; toppersystemnet) Gecko/20100101 Firefox/72.0";}else{val_header_send_toppersystem="Mozilla/5.0 (AppleWebKit/537.36 (KHTML, like Gecko, toppersystemnet) Chrome/120.0.0.0 Safari/537.36";}
let headers=new Headers({'Accept':'*/*',"User-Agent":val_header_send_toppersystem});const formData=new FormData();formData.append("toppersystem_update","ok");fetch(url,{method:"POST",body:formData,mode:"cors",cache:"no-cache",credentials:"same-origin",headers:headers}).then(function(response){return response.text()}).then(function(html){var nchartpageoriginal=html.length;if(document.getElementById('clhts')){document.getElementById('clhts').value=nchartpageoriginal;setTimeout("BodySizeCalculateTS2(\""+lang+"\")",800);}}).catch(function(err){var txtts1;if(lang=="it"){txtts1="Spiacenti! Riprova più tardi";}else if(lang=="ar"){txtts1="آسف! حاول لاحقا";}else if(lang=="de"){txtts1="Es tut uns leid! Versuche es später";}else if(lang=="es"){txtts1="¡Lo siento! Intenta más tarde";}else if(lang=="fr"){txtts1="Pardon! Essayer plus tard";}else if(lang=="hi"){txtts1="माफ़ करना! बाद में प्रयास करें";}else if(lang=="ja"){txtts1="ごめん！ 後で試す";}else if(lang=="pl"){txtts1="Przepraszam! Spróbuj później";}else if(lang=="pt"){txtts1="Desculpe! Tente depois";}else if(lang=="ru"){txtts1="Извиняюсь! Попробуй позже";}else if(lang=="zh"){txtts1="对不起！ 等会再试";}else if(lang=="he"){txtts1="מצטער! נסה מאוחר יותר";}else if(lang=="la"){txtts1="Ignosce! Conare postea";}else{txtts1="Sorry! Try later";}
if(document.getElementById('co2tsresult')){document.getElementById('co2tsresult').innerHTML="<span>&#127811; "+txtts1+"</span>";}
setTimeout("CloseResultCo2TS()",1400);})}}}else{setTimeout("BodySizeCalculateTS2(\""+lang+"\")",800);}}}}
function BodySizeCalculateTS2(lang){if(ControllerFunctionTS()==true){var totalReseourcesParser="";if(performance.getEntriesByType('resource')){if(performance.getEntriesByType('resource').length>0){var res=performance.getEntriesByType('resource');var totalReseources="";for(var icsyl=0;icsyl<res.length;icsyl++){if(res[icsyl]){totalReseources=totalReseources+res[icsyl].name+"||||"+res[icsyl].decodedBodySize+"\n";}}}else{var totalReseources="";}}else{var totalReseources="";}
if(performance.getEntriesByType('navigation')){if(performance.getEntriesByType('navigation').length>0){var res2=performance.getEntriesByType('navigation');var totalNavigation="";for(var icsylm=0;icsylm<res2.length;icsylm++){if(res2[icsylm]){totalNavigation=totalNavigation+res2[icsylm].name+"||||"+res2[icsylm].decodedBodySize+"\n";}}}else{var totalNavigation="";}}else{var totalNavigation="";}
var resend_ts=document.getElementById('rsdts').value.trim();var nfileorig=0;for(var im=0;im<document.images.length;im++){if(document.images[im].srcset){if(totalReseourcesParser.replace(document.images[im].srcset,'')===totalReseourcesParser){totalReseourcesParser=totalReseourcesParser+document.images[im].srcset+"\n";nfileorig++;}}else if(document.images[im].src){if(totalReseourcesParser.replace(document.images[im].src,'')===totalReseourcesParser){totalReseourcesParser=totalReseourcesParser+document.images[im].src+"\n";nfileorig++;}}else{}}
var x=document.scripts;var i;for(i=0;i<x.length;i++){if(x[i].src){if(totalReseourcesParser.replace(x[i].src,'')===totalReseourcesParser){totalReseourcesParser=totalReseourcesParser+x[i].src+"\n";nfileorig++;}}}
for(var ics=0;ics<document.styleSheets.length;ics++){if(document.styleSheets[ics]){var sheet=document.styleSheets[ics];if(sheet.href){if(totalReseourcesParser.replace(sheet.href,'')===totalReseourcesParser){totalReseourcesParser=totalReseourcesParser+sheet.href+"\n";nfileorig++;}}}}
var css="";var css_inline="";styletags=document.getElementsByTagName("style");for(var i=0;i<styletags.length;i++){if(styletags[i]){css_inline=styletags[i].innerHTML;arr_valore=css_inline.split(";");for(a=0;a<=arr_valore.length;a++){if(arr_valore[a]){if(arr_valore[a].trim()!=""){newtxtarray=arr_valore[a].replace('url(','');if(arr_valore[a]!=newtxtarray){css+=arr_valore[a]+";";}
newtxtarray="";arr_valore[a]="";}}}
css_inline="";}}
var nthispage=document.getElementsByTagName('body')[0].outerHTML.length;if(totalReseources.replace('||||undefined','')!==totalReseources){var newsheet="";txtarr=totalReseources.split("\n");for(var icsy=0;icsy<txtarr.length;icsy++){if(txtarr[icsy]){var sheet=txtarr[icsy];if(sheet!=""){newsheet=sheet.split("||||")[0];if(newsheet!=""){if(totalReseourcesParser.replace(newsheet,'')===totalReseourcesParser){totalReseourcesParser=totalReseourcesParser+newsheet+"\n";}}
newsheet="";}}}
totalReseources="";var urlthispage=window.location.href;totalNavigation=urlthispage+"||||"+nthispage+"\n";}
var rappcache=0;if((resend_ts!="")&&(lang!="")){if(document.getElementById('clhts')){if((document.getElementById('clhts').value.trim()!="")){var http=new XMLHttpRequest();http.onreadystatechange=function(){if(http.readyState==4&&http.status==200){if(http.responseText!=""){document.getElementById('co2tsresult').innerHTML=DecodeHTMLentytiesTS(http.responseText.trim());}}else if(http.readyState==4&&http.status!=200){var txtts1;if(lang=="it"){txtts1="Spiacenti! Riprova più tardi";}else if(lang=="ar"){txtts1="آسف! حاول لاحقا";}else if(lang=="de"){txtts1="Es tut uns leid! Versuche es später";}else if(lang=="es"){txtts1="¡Lo siento! Intenta más tarde";}else if(lang=="fr"){txtts1="Pardon! Essayer plus tard";}else if(lang=="hi"){txtts1="माफ़ करना! बाद में प्रयास करें";}else if(lang=="ja"){txtts1="ごめん！ 後で試す";}else if(lang=="pl"){txtts1="Przepraszam! Spróbuj później";}else if(lang=="pt"){txtts1="Desculpe! Tente depois";}else if(lang=="ru"){txtts1="Извиняюсь! Попробуй позже";}else if(lang=="zh"){txtts1="对不起！ 等会再试";}else if(lang=="he"){txtts1="מצטער! נסה מאוחר יותר";}else if(lang=="la"){txtts1="Ignosce! Conare postea";}else{txtts1="Sorry! Try later";}
if(document.getElementById('co2tsresult')){document.getElementById('co2tsresult').innerHTML="<span>&#127811; "+txtts1+"</span>";}
setTimeout("CloseResultCo2TS()",1400);}else{if(http.readyState==1){}else if(http.readyState==2){}else if(http.readyState==3){}}}
var clhts=document.getElementById('clhts').value.trim();var url=document.getElementById('rsdajxts').value.trim();var params="action=componentstoppersystem34ajax&totalNavigation="+encodeURIComponent(totalNavigation)+"&totalReseources="+encodeURIComponent(totalReseources)+"&clhts="+encodeURIComponent(clhts)+"&hreflang="+encodeURIComponent(lang)+"&totalReseourcesParser="+encodeURIComponent(totalReseourcesParser)+"&rsd="+encodeURIComponent(resend_ts)+"&rsdcts="+encodeURIComponent(document.getElementById('rsdcts').value.trim())+"&ntpts="+encodeURIComponent(nthispage)+"&css="+encodeURIComponent(css);http.open("POST",url,true);http.setRequestHeader("Content-type","application/x-www-form-urlencoded");http.send(params);}}}}}
async function startco2ts(){if(ControllerFunctionTS()==true){if(document.body){if(document.getElementById('clhts')){if((document.getElementById('clhts').value.trim()!="")){if(!document.getElementById('co2ts')){var lang=navigator.language||navigator.userLanguage;var newlang=lang.replace(/_/,'-');var hreflang_toppersystem=newlang.split("-")[0];var ltl;if(hreflang_toppersystem=="it"){ltl="it";}else if(hreflang_toppersystem=="ar"){ltl="ar";}else if(hreflang_toppersystem=="de"){ltl="de";}else if(hreflang_toppersystem=="es"){ltl="es";}else if(hreflang_toppersystem=="fr"){ltl="fr";}else if(hreflang_toppersystem=="hi"){ltl="hi";}else if(hreflang_toppersystem=="ja"){ltl="ja";}else if(hreflang_toppersystem=="pl"){ltl="pl";}else if(hreflang_toppersystem=="pt"){ltl="pt";}else if(hreflang_toppersystem=="ru"){ltl="ru";}else if(hreflang_toppersystem=="zh"){ltl="zh";}else if(hreflang_toppersystem=="he"){ltl="he";}else if(hreflang_toppersystem=="la"){ltl="la";}else{ltl="en";}
var add=document.createElement("div");add.setAttribute("id","co2ts");add.setAttribute("class","co2ts");add.innerHTML="<span onclick=\"BodySizeCalculateTS('"+ltl+"')\">&#127811;</span>";document.body.appendChild(add);}}}}}}
document.addEventListener("DOMContentLoaded",startco2ts());
//-->